spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pizzaapp}
    username: ${DB_USER:pizzaapp}
    password: ${DB_PASSWORD:pizzaapp}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8080
